# Generated by Django 6.0.4 on 2026-04-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(default=''),
        ),
    ]
