# Generated by Django 6.0.4 on 2026-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_resume_extracted_text_resume_found_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.CharField(default='Fresher', max_length=200),
        ),
    ]
