# Generated by Django 6.0.4 on 2026-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_resume_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jd_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='matching_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
