# Generated by Django 6.0.4 on 2026-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_resume_jd_skills_resume_matching_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_mathching_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
